apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # Thses are replica set labels
  labels:
    purpose: helm-demo
    project: roboshop
spec: 
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # These labels are used to select pods
    matchLabels:
      purpose : helm-demo
      project: roboshop
  # Pod definition    
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose : helm-demo
        project: roboshop
    spec: 
      containers: 
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}